import type { Metadata } from "next";

/**
 * Centralised metadata builder.
 *
 * Fixes three site-wide SEO defects in one place:
 *  1. Brand duplication — the root title template appends " · Zeppstr", so any
 *     page title that ALREADY contains "Zeppstr" rendered as "… · Zeppstr · Zeppstr".
 *     cleanTitle() strips a trailing brand suffix before the template runs.
 *  2. Missing canonical — every page routed through this helper gets
 *     alternates.canonical set from its `path`.
 *  3. Overlong title/description — trimmed to SERP-safe lengths at word boundaries.
 *
 * og:image / twitter image are supplied site-wide by app/opengraph-image.tsx
 * (Next.js file convention), so they are not set here.
 */

// Matches a trailing "— Zeppstr", "| Zeppstr", "· Zeppstr",
// optionally "Growth Media", at the end of a title.
const BRAND_SUFFIX = /\s*[—\-|·]\s*Zeppstr(?:\s+Growth\s+Media)?\s*$/i;

// Page-title portion kept ≤ 50 chars so that after the "%s · Zeppstr"
// template (+10 chars) the rendered <title> stays ≤ ~60.
const MAX_TITLE = 50;
const MAX_DESC = 155;

// Site-wide default share image (generated by app/opengraph-image.tsx).
// A child metadata object that sets its own openGraph replaces the parent's
// images, so the default is re-applied here for every page routed through
// buildMetadata. A page can still override by passing openGraph.images.
const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Zeppstr — Your Growth Partner in Digital Marketing & SEO",
};

function trimAtWord(value: string, max: number): string {
  const s = value.trim().replace(/\s+/g, " ");
  if (s.length <= max) return s;
  return s.slice(0, max).replace(/\s+\S*$/, "").trim();
}

export function cleanTitle(title: string): string {
  return trimAtWord(title.replace(BRAND_SUFFIX, "").trim(), MAX_TITLE);
}

export function cleanDescription(description?: string): string | undefined {
  if (!description) return description;
  return trimAtWord(description, MAX_DESC);
}

type BuildMetadataInput = Metadata & { path: string };

/**
 * Wrap a page's metadata object and add path -> canonical.
 * Any extra Metadata fields (keywords, robots, etc.) pass through untouched.
 */
export function buildMetadata(input: BuildMetadataInput): Metadata {
  const { path, title, description, openGraph, twitter, alternates, ...rest } =
    input;

  const cleanedTitle =
    typeof title === "string" ? cleanTitle(title) : title;
  const cleanedDescription =
    typeof description === "string" ? cleanDescription(description) : description;

  return {
    ...rest,
    title: cleanedTitle,
    description: cleanedDescription,
    alternates: { ...(alternates ?? {}), canonical: path },
    openGraph: {
      type: "website",
      url: path,
      title: (cleanedTitle as string) ?? undefined,
      description: (cleanedDescription as string) ?? undefined,
      images: [DEFAULT_OG_IMAGE],
      ...(openGraph ?? {}),
    },
    twitter: {
      card: "summary_large_image",
      title: (cleanedTitle as string) ?? undefined,
      description: (cleanedDescription as string) ?? undefined,
      images: ["/opengraph-image"],
      ...(twitter ?? {}),
    },
  };
}
